export interface CategoryQuestionBank{
    categoryName: string;
    questions: string[];
}

export const STARTERS = {
    categoryName: "Starters",
    questions: [
        "What are your hobbies?", 
        "Do you collect anything?", 
        "What are you passionate about?", 
        "What is your most prized possession?", 
        "What is the greatest accomplishment of your life?", 
        "What is on your bucket list?", 
        "What is your favorite recent memory?", 
        "What is your best childhood memory?", 
        "What is your favorite holiday?", 
        "Who knows you best?", 
        "What family member are you closest to?", 
        "What skill would you most like to learn?", 
        "Where is the coolest place you traveled?", 
        "What does your average weekend look like?", 
        "Tell me about your longest running friendship with someone?", 
        "What is your earliest memory?", 
        "What makes you unique?", 
        "Who is your hero?", 
        "Who is the smartest person you ever met?", 
        "What is one thing that instantly makes your day better?", 
        "When did you first feel like an adult?", 
        "Whose opinion do you care most about?", 
        "What is the most important decision you have ever made so far?", 
        "Aside from necessities, what one thing could you not go a day without?", 
        "What do you enjoy spending money on?", 
        "What is something that always makes you smile?", 
        "What are you most thankful for?", 
        "What are you most looking forward to?", 
        "What do you wish more people understand about you?", 
        "What is the greatest challenge or struggle you have ever faced?", 
        "What is the biggest risk you ever took?", 
    ]
};
export const BASIC = {
    categoryName: "Basic",
    questions: [
        "What is your favorite color?",
        "What is your favorite animal?",
        "Do you have any pets?",
        "Do you have brothers or sisters?",
        "How old are you?",
        "When is your birthday?",
        "What is the farthest you have traveled from home?",
        "What is your favorite summer activity?",
        "What is your favorite winter activity?",
        "What is your favorite food?",
        "If you could choose a new name, which one would it be?",
        "Who is your favorite superhero?",
        "Who is your favorite Disney character?",
        "What is the best vacation you have ever taken?",
        "What is the silliest thing you can imagine?",
        "What are you afraid of?",
        "What is your favorite snack?",
        "What is your favorite story?",
        "What is the bravest thing you ever did?",
        "Who is the best cartoon character?",
        "If you could make one rule for everyone in the world to follow, what would it be?",
        "If you could own any animal as a pet, what would you choose?",
        "What is the coolest thing you ever made?",
        "What is your favorite way to spend an afternoon?",
        "What are you most excited about right now?",
        "What is your favorite sport?",
        "What is your favorite song?",
        "Show me your best dance move.",
        "What makes you awesome?",
        "What is your favorite outfit?",
        "If you could redesign your bedroom, what would you add?",
        "Describe your favorite stuffed animal.",
        "What is your favorite toy?",
        "What is your favorite thing to do with your parents?",
    ]
};
export const FUN = {
    categoryName: "Fun",
    questions: [
        "What is the most ridiculous nightmare you have ever had?",
        "Tell us an embarrassing story.",
        "Explain an inside joke you have with a friend or family member.",
        "If your pet could talk, what do you think they might say about you?",
        "Tell me your life story in exactly one sentence.",
        "What is the strangest coincidence that ever happened to you?",
        "What is your favorite random fact?",
        "What is your useless talent?",
        "What is the strangest food combination you enjoy?",
        "What would your drag queen name be?",
        "If you could choose one superpower, what would it be?",
        "What is your strangest irrational fear?",
        "Describe your most eccentric family member.",
        "Have you ever met a celebrity? Which celebrity would you like to meet?",
        "What is the craziest thing you ever did on a dare?",
        "What is the grossest thing you would do for $100?",
        "What songs are on the soundtrack to your life?",
        "What actor would you choose to play you in your biopic?",
        "What is your go-to karaoke song?",
        "If you were a superhero, who would be your archnemesis?",
        "Create and describe an undercover alias.",
        "What is your most random impulse buy?",
        "What did you do as a teenager that makes you cringe now?",
        "What would your warning label say?",
        "What is your guilty pleasure?",
        "What emoji do you use most often?",
        "Does your family practice any unusual traditions?",
        "A genie grants you the ability to have infinite amounts of one item. What is it?",
        "What is your favorite random fact?",
        "What is your favorite joke?",
        "What is the best Halloween costume you ever wore?",
        "What is the most awkward situation you ever found yourself in?",
        "What is the most ridiculous thing you believed as a child?",
        "What is the most outrageous lie you told a child?",
        "What is the dumbest way you injured yourself?",
        "How do you waste time most often?",
        "What is the worst outfit you ever wore?",
    ]
}; 
export const EFFECTIVE = {
    categoryName: "Effective",
    questions: [
        "Do you have a significant other?",
        "Do you have kids?",
        "Who do you live with?",
        "Where did you grow up?",
        "What is the best place you ever traveled to?",
        "What do you think would most impress your five year old self? Your 15 year old self?",
        "What kind of elderly person do you hope to be?",
        "What is your favorite website?",
        "What is your favorite season?",
        "What book changed your life?",
        "How do you prefer to exercise?",
        "What movie do you wish you could watch again for the first time?",
        "What is one story you love to tell, but rarely get the chance?",
        "What is one question you wish people would ask you more?",
        "What is one question you wish people would ask you less?",
        "What is your favourite song?",
        "What was the first concert you attended? The best concert?",
        "What is your favourite quote?",
        "What is the last book you read?",
        "What is the last TV show you binged watched?",
        "What movie could you quote by heart?",
        "What do you dislike that everyone else seems to like?",
        "What do you like that everyone else seems to dislike?",
        "What makes you happiest?",
        "Have you ever met a celebrity? Which celebrity would you like to meet?",
        "Describe yourself in three words.",
        "What is the best idea you have ever had for a business?",
        "If given the opportunity, what book would you write?",
        "What is the strangest food combination you enjoy?",
        "What is your favorite kind of cuisine?",
        "What is the best meal you have ever eaten?",
        "If you won the lottery, what would you do first?",
        "What is your favorite cocktail?",
        "Do you have any tattoos? If not, are there any tattoos you want?",
        "What are you allergic to?",
    ]
};
export const GOOD = {
    categoryName: "Good",
    questions: [
        "What are your hobbies?", 
        "Do you collect anything?", 
        "What are you passionate about?", 
        "What is your most prized possession?", 
        "What is the greatest accomplishment of your life?", 
        "What is on your bucket list?", 
        "What is your favorite recent memory?", 
        "What is your best childhood memory?", 
        "What is your favorite holiday?", 
        "Who knows you best?", 
        "What family member are you closest to?", 
        "What skill would you most like to learn?", 
        "Where is the coolest place you traveled?", 
        "What does your average weekend look like?", 
        "Tell me about your longest running friendship with someone?", 
        "What is your earliest memory?", 
        "What makes you unique?", 
        "Who is your hero?", 
        "Who is the smartest person you ever met?", 
        "What is one thing that instantly makes your day better?", 
        "When did you first feel like an adult?", 
        "Whose opinion do you care most about?", 
        "What is the most important decision you have ever made so far?", 
        "Aside from necessities, what one thing could you not go a day without?", 
        "What do you enjoy spending money on?", 
        "What is something that always makes you smile?", 
        "What are you most thankful for?", 
        "What are you most looking forward to?", 
        "What do you wish more people understand about you?", 
        "What is the greatest challenge or struggle you have ever faced?", 
        "What is the biggest risk you ever took?", 
    ]
};
export const INTERESTING = {
    categoryName: "Interesting",
    questions: [
        "If you could speak to one deceased person for thirty seconds, who would it be and what would you say?", 
        "If you could travel to the past and change one event, would you? Which one? Why?", 
        "What is the best advice you haves ever received?", 
        "What is the worst advice you have ever received?", 
        "For what in your life do you feel most grateful?", 
        "If you could change anything about the way your parents raised you, what would it be?", 
        "Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?", 
        "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?", 
        "What area of your life would you most like to improve?", 
        "If you could switch lives with any one person for one day, who would you choose?", 
        "What is your definition of success?", 
        "How has your perspective on the world changed over time?", 
        "Do you believe that people can change?", 
        "Do you believe you will accomplish your dreams?", 
        "What was the scariest moment in your life so far?", 
        "What is your biggest regret to date?", 
        "Whose death hit you hardest?", 
        "Do you believe in free will?", 
        "Do you believe in destiny?", 
        "If you could relive one moment in your life, which would it be?", 
        "What is your most cherished belief?", 
        "Where do you think we go when we die?", 
        "What do you think is the meaning of life?", 
    ]
};
export const WORK = {
    categoryName: "Work",
    questions: [
        "What is your position?", 
        "What was your last position?", 
        "What was your first job?", 
        "Did you go to college? If yes, what college? What was your major?", 
        "Do you work better in the morning or at night?", 
        "Do you prefer working remotely or in the office?", 
        "Do you prefer group work or solo work?", 
        "Emails, texts, or phone calls?", 
        "How do you take your coffee?", 
        "What is your funniest work story to date?", 
        "What was the biggest mistake you ever made at work?", 
        "What was the hardest lesson you learned so far?", 
        "Describe the best team you have worked with.", 
        "Describe the best manager you have worked for.", 
        "What is the best team outing you have ever attended?", 
        "What is your dream role?", 
        "Describe the most interesting coworker you have worked with.", 
        "What is your all time favorite project?", 
        "If money were no issue, what would you do with your time?", 
        "If you did not work in this industry, what field would you pursue?", 
        "Describe your dream boss.", 
        "Describe your nightmare boss.", 
        "If you lived 500 years ago, what do you think your profession would be?", 
        "If you lived 500 years in the future, what do you think your profession would be?", 
        "What do you hope your coworkers say about you at your retirement party?", 
        "If money were no object, how would you spend your time?", 
        "Why did you pick this profession?", 
        "What motivates you?", 
        "What inspires you?", 
        "What scares you, professionally speaking?", 
        "What is your dream project?", 
        "Name your dream team.", 
        "What career advice would you give to your younger self?", 
        "How do you deal with work stress?", 
        "You can ban one question from the interview process forever. Which one do you choose?", 
        "If you were to start your own business, what kind of company would you create?", 
        "Would you rather win the lottery or work at the perfect job? Why?", 
        "What’s your favorite way to spend a day off?", 
    ]
};
export const COUPLES = {
    categoryName: "Couples",
    questions: [
        "What is your position?", 
        "What was your last position?", 
        "What was your first job?", 
        "Did you go to college? If yes, what college? What was your major?", 
        "Do you work better in the morning or at night?", 
        "Do you prefer working remotely or in the office?", 
        "Do you prefer group work or solo work?", 
        "Emails, texts, or phone calls?", 
        "How do you take your coffee?", 
        "What is your funniest work story to date?", 
        "What was the biggest mistake you ever made at work?", 
        "What was the hardest lesson you learned so far?", 
        "Describe the best team you have worked with.", 
        "Describe the best manager you have worked for.", 
        "What is the best team outing you have ever attended?", 
        "What is your dream role?", 
        "Describe the most interesting coworker you have worked with.", 
        "What is your all time favorite project?", 
        "If money were no issue, what would you do with your time?", 
        "If you did not work in this industry, what field would you pursue?", 
        "Describe your dream boss.", 
        "Describe your nightmare boss.", 
        "If you lived 500 years ago, what do you think your profession would be?", 
        "If you lived 500 years in the future, what do you think your profession would be?", 
        "What do you hope your coworkers say about you at your retirement party?", 
        "If money were no object, how would you spend your time?", 
        "Why did you pick this profession?", 
        "What motivates you?", 
        "What inspires you?", 
        "What scares you, professionally speaking?", 
        "What is your dream project?", 
        "Name your dream team.", 
        "What career advice would you give to your younger self?", 
        "How do you deal with work stress?", 
        "You can ban one question from the interview process forever. Which one do you choose?", 
        "If you were to start your own business, what kind of company would you create?", 
        "Would you rather win the lottery or work at the perfect job? Why?", 
        "What’s your favorite way to spend a day off?", 
    ]
};
export const STUDENTS = {
    categoryName: "Students",
    questions: [
        "What is your favorite school subject?", 
        "Do you play any sports?", 
        "Do you play any instruments?", 
        "Do you belong to any extracurricular activities?", 
        "What is your favorite lunch?", 
        "Who is your favorite teacher so far?", 
        "What is the most surprising fact you learned?", 
        "If you could change one thing about school, what would it be?", 
        "What class do you wish this school offered?", 
        "Do you prefer to work individually or in groups?", 
        "Would you rather sit in desks, at tables, on the floor, or in auditorium seats?", 
        "Do you prefer distance learning or in person learning?", 
        "What is your favorite part about school?", 
        "What is your least favorite part about school?", 
        "What is the most interesting thing you see on the way to school?", 
        "What is your standard morning routine?", 
        "What is the first thing you do upon arriving home after school?", 
        "Do you work? If so, where?", 
        "Do you volunteer? If so, where? If not, where would you like to volunteer?", 
        "Describe your dream field trip.", 
        "Do you prefer school uniforms or a relaxed dress code?", 
        "Do you speak any other languages? Which languages would you most like to learn?", 
        "What was the most unexpected thing you learned in school so far this year?", 
        "If I asked you to teach a class on any subject, what topic would you choose?", 
        "What is your best study tip?", 
        "What is the best project you ever turned in?", 
        "If you could take a class with any expert, who would you choose?", 
        "If you could attend any fictional school, which one would you choose?", 
    ]
};
export const TRUTH = {
    categoryName: "Yes or no",
    questions: [
        "What's the last lie you told?",
        "What was the most embarrassing thing you've ever done on a date?",
        "Have you ever accidentally hit something (or someone!) with your car?",
        "Name someone you've pretended to like but actually couldn't stand.",
        "What's your most bizarre nickname?",
        "What's been your most physically painful experience?",
        "What bridges are you glad that you burned?",
        "What's the craziest thing you've done on public transportation?",
        "If you met a genie, what would your three wishes be?",
        "If you could write anyone on Earth in for President of the United States, who would it be and why?",
        "What's the meanest thing you've ever said to someone else?",
        "Who was your worst kiss ever?",
        "What's one thing you'd do if you knew there no consequences?",
        "What's the craziest thing you've done in front of a mirror?",
        "What's the meanest thing you've ever said about someone else?",
        "What's something you love to do with your friends that you'd never do in front of your partner?",
        "Who are you most jealous of?",
        "What do your favorite pajamas look like?",
        "Have you ever faked sick to get out of a party?",
        "Who's the oldest person you've dated?",
        "How many selfies do you take a day?",
        "Meatloaf says he'd do anything for love, but he won't do \"that.\" What's your \"that?\"",
        "How many times a week do you wear the same pants?",
        "Would you date your high school crush today?",
        "Where are you ticklish?",
        "Do you believe in any superstitions? If so, which ones?",
        "What's one movie you're embarrassed to admit you enjoy?",
        "What's your most embarrassing grooming habit?",
        "When's the last time you apologized? What for?",
        "How do you really feel about the Twilight saga?",
        "Where do most of your embarrassing odors come from?",
        "Have you ever considered cheating on a partner?",
        "Have you ever cheated on a partner?",
        "Boxers or briefs?",
        "Have you ever peed in a pool?",
        "What's the weirdest place you've ever grown hair?",
        "If you were guaranteed to never get caught, who on Earth would you murder?",
        "What's the cheapest gift you've ever gotten for someone else?",
        "What app do you waste the most time on?",
        "What's the weirdest thing you've done on a plane?",
        "Have you ever been nude in public?",
        "How many gossip blogs do you read a day?",
        "What is the youngest age partner you'd date?",
        "Have you ever picked your nose in public?",
        "Have you ever lied about your age?",
        "If you had to delete one app from your phone, which one would it be?",
        "What's your most embarrassing late-night purchase?",
        "What's the longest you've gone without showering?",
        "Have you ever used a fake ID?",
        "Who's your hall pass?",
        "Be honest: Do you have a favorite child?",
        "Which of your family members annoys you the most and why?",
        "What is your greatest fear in a relationship?",
        "What's your biggest pet peeve about the person to your left?",
        "What's the most embarrassing text in your phone right now?",
        "Have you ever seen a dead body?",
        "What celebrity do you think is overrated?",
        "Have you ever lied to your boss?",
        "Have you ever stolen something from work?",
        "What's the longest you've gone without brushing your teeth?",
        "What's your biggest regret in life?",
        "Who would you hate to see naked?",
        "Describe the weirdest thing you've ever done while inebriated.",
        "Have you ever regifted a present?",
        "Would you break up with your partner for $1 million?",
        "Have you ever had a crush on a coworker?",
        "Do you still have feelings for any of your exes?",
        "What's the smallest tip you've ever left at a restaurant?",
        "Have you ever regretted something you did to get a crush or partner's attention?",
        "What's one job you could never do?",
        "Have you ever ghosted a friend?",
        "Have you ever ghosted a partner?",
        "What's the most scandalous photo in your cloud?",
        "If you switched genders for a day, what would you do?",
        "How many photo editing apps do you have on your phone?", 
        "How many pairs of granny panties do you own?",
        "What are your favorite and least favorite of your body parts?",
        "When's the last time you got dumped?",
        "What's the most childish thing you still do?",
        "When's the last time you dumped someone?",
        "If you had to pick someone in this room to be your partner on a game show, who would it be and why?",
        "Would you date someone shorter than you?",
        "Have you ever lied for a friend?",
        "Name one thing you'd change about every person in this room.",
        "When's the last time you made someone else cry?",
        "What's the most embarrassing thing you've done in front of a crowd?",
        "If you could become invisible, what's the worst thing you'd do?",
        "After you've dropped a piece of food, what's the longest time you've left it on the floor before eating it?",
        "What's one thing in your life you wish you could change?",
        "If you could date two people at once, would you do it? If so, who?",
        "What's something that overwhelms you?",
        "What was the greatest day of your life?",
        "What's one useless skill you'd love to learn anyway?",
        "If I went through your cabinets, what's the weirdest thing I'd find?",
        "Have you ever farted and blamed it on someone else?",
        "What's the worst thing you've ever done at work?",
        "How many people have you kissed?",
        "What's your number?",
        "Have you ever gotten mad at a friend for posting an unflattering picture of you?",
        "What's your most absurd dealbreaker?",
        "Who in this room would you list as your emergency contact?",
        "What's something you would die if your mom found out about?",
        "What's the scariest thing that's ever happened to you?",
        "If you could set anyone here up with your best friend, who would it be and why?",
        "How often do you wash your sheets?",
        "Have you ever farted in an elevator?",
        "Who was your first love?",
        "What's the last purchase you regretted?",
        "Have you ever sent a sext?",
        "Have you ever sent a sext to the wrong person? Who?",
        "What's the weirdest dream you've ever had?",
        "Have you ever had a one-night stand?",
        "Are you scared of getting old?",
        "What do you want on your tombstone?",
        "If you had one week to live and you had to marry someone in this room, who would it be?",
        "What's the last movie that made you cry?",
        "List one positive and one negative thing about everyone in the room.",
        "When was your first time?",
        "Who was your first?",
        "What's the most sinful thing you've done in a house of worship?",
        "Who would you call to help bury a body?",
        "Who would call you to help bury a body? Would you do it?",
        "When's the last time you cried and why?",
        "What's your favorite possession?",
        "Has anyone ever walked in on you in the bathroom?",
        "Who in this group would you want to swap lives with for a week?",
        "What was your biggest fear as a child?",
        "What's your biggest fear today?",
        "What's the most embarrassing thing your parents have caught you doing?",
        "Name a band you only pretend to like.",
        "What's the last song that made you cry?",
        "Have you ever had a wardrobe malfunction?",
        "What's the last thing you Googled?",
        "What is that one thing you would never do for all the money in the world?",
        "Who is your favorite person in your immediate family?",
        "If you could only hear one song for the rest of your life, what would it be?",
        "When's the last time your partner embarrassed you?",
        "What's the last YouTube video you watched?",
        "What's the hardest drug you've ever tried?",
        "When's the last time you peed your pants?",
        "Who in this room would be your one phone call if you were in jail?",
        "Who do you most often text on the toilet?",
        "What's the craziest thing you've ever done in a movie theater?",
        "What's the craziest thing that has happened to you in a mall?",
        "How long was your longest relationship?",
        "What's your biggest insecurity?",
        "Have you ever been arrested?",
        "Who's the most surprising person to ever slide into your DMs?",
        "Where's one place you're dying to visit?",
        "What word do you hate the most?",
        "What's the most embarrassing thing you've ever posted on social media?",
        "Have you ever kept a library book? For how long?",
        "If you could hire someone to do one thing for you, what would it be?",
        "Would you ever consider being a nudist?",
        "Have you ever lied on your resume?",
        "What's the best lie you've ever told anyone?",
        "Who's the last person you lurked on social media?",
        "What's your most embarrassing childhood memory?",
        "Have you ever pretended to not get a text to get out of doing something?",
        "What's the weirdest thing you've ever done in a bathroom?",
        "What's the most insane thing you've done to get out of a speeding ticket?",
        "Do you have any hidden talents? What are they?",
        "When's the last time you got caught in a lie?",
        "How do you really feel about your mother-in-law?",
        "What do you think happens when you die?",
        "When's the last time you watched an adult movie?",
        "Have you ever been in a fight?",
        "Would you marry someone rich even if you weren't in love with them?",
        "Have you ever been caught checking someone out?",
        "What's the worst advice you've ever given someone else?",
        "What's the worst advice someone else has ever given you?",
        "Would you volunteer as tribute for anyone in this room in The Hunger Games?",
        "Is there an ex with whom you'd consider reconciling?",
        "What's the weirdest thing you do while driving?",
        "Who's the last person who called you?",
        "When's the last time you wanted to hit somebody?",
        "What's the grossest smell that you secretly enjoy?",
        "What's the biggest prank you've ever played on someone?",
        "What's one thing about your partner that you find least attractive?",
        "When was the last time you were really angry? Why?",
        "What's your least favorite memory from college?",
        "What's the grossest thing that you do alone?",
        "Have you ever intentionally sabotaged a coworker?",
        "What's your favorite guilty pleasure song?",
        "Would you ever get plastic surgery?",
        "Have you ever had a near-death experience?",
        "What's a skill you wish you had?",
        "Have you ever compromised your morals for money? How?",
        "Who was the last person you said, \"I love you\" to?",
        "What was your first heartbreak?",
        "Have you ever broken someone's heart?",
        "Have you ever peed in the shower?",
        "What's the most bogus rumor you've ever heard about yourself?",
        "What's the most bogus rumor you've ever spread or heard about someone else?",
        "When and where was your first kiss? Who was it with?",
        "Do you think cheating can ever be justified? How?",
        "Have you ever thrown up in public?",
        "When's the last time you got rejected?",
        "What's the most common misconception about you?",
        "Have you ever seriously injured another person?",
        "When did you stop believing in Santa Claus?",
        "What's one responsibility you wish you didn't have?",
        "Who is the best kisser you've ever had?",
        "What's the scariest thing you've ever done?",
        "Have you ever had a paranormal experience?",
        "Have you ever gotten blackout drunk?",
        "Do you believe in aliens?",
        "What's the pettiest thing you've ever done?",
        "What's something you've done that you still feel guilty about?",
        "Have you ever gone skinny dipping?",
        "What is the worst date you've ever been on?",
        "Do you secretly dislike any of your friends' kids?",
        "What's the weirdest thing you've ever collected?",
        "What's the weirdest thing you've ever said to a stranger?",
        "Who in this room do you trust the least?",
        "What's the most inappropriate time you've ever laughed?",
        "What's your best pickup line?",
        "What's your sleaziest pickup line?",
        "What's the weirdest place you've ever given or gotten someone's number?",
        "What's the dumbest thing you've ever lied about?",
        "Have you ever said, \"I love you\" and not really meant it? To whom?",
        "What's your least favorite memory from high school?",
        "What's the worst present someone has ever given you?",
        "When's the last time you shared a toothbrush with someone else?",
        "Have you ever had a crush on a boss or teacher?",
        "What's the worst present you've ever given someone else?",
        "What's the weirdest thought you've had sitting on a toilet?",
        "What song do you sing most in the shower?",
        "Do you have a work spouse?",
        "What's the cruelest thing you've ever done or said to a romantic partner?",
        "Who's the person you most regret hooking up with?",
        "What's something you're embarrassed that you're good at?",
        "What was your most humbling moment?",
        "Who would you bring with you on a deserted island?",
        "What's the worst decision one of the other players has ever made?",
        "Have you ever been fired from a job?",
        "Have you ever let someone take the blame for something you did?",
        "What's the most ridiculous thing you have an emotional attachment to?",
        "Have you ever pooped your pants as an adult?",
        "What's something you've done that you'd judge someone else for doing?",
        "What's something weird you do in your sleep?",
        "How long have you had your oldest pair of underwear?",
        "Who's your hero?",
        "What's something you know you need to do but aren't looking forward to at all?",
        "What's the biggest secret you've kept from your parents?",
        "What's the most offensive joke you've found funny?",
        "What are you most proud of in your life?",
        "When's the last time you lurked an ex on social media?",
        "Would you ever get a prenup?",
        "If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?",
    ]
};

export const PHILOSOPHICAL = {
    categoryName: "Philosophical",
    questions: [
        "What Is the Meaning of Life?",
        "What is the nature of reality?",
        "Why did consciousness emerge?",
        "How to fully understand oneself?",
        "Is there life after death?",
        "Can people ever truly change?",
        "Are all human beings fundamentally equal, or are some people intrinsically more valuable than others?",
        "Is there such a thing as absolute reality or is everything just subjectively defined by our own minds?",
        "If time doesn’t have an end, does that mean we all live on forever?",
        "Do we create our own reality through our perception and thoughts, or are we bound by objective laws that cannot be changed by thought alone?",
        "How much control do we have over our own lives and choices and are some people at an advantage because they control more of their lives than others do?",
        "Is it possible to be absolutely certain about anything?",
        "Is it true that “nothing is true”? If so, wouldn’t that make the question itself false? And if not, then what is true?",
        "What if someone was born without the ability to feel any physical pain whatsoever—is it possible they might even die without knowing something was wrong until too late?",
        "Do we really own anything in this world or are we just renting everything from nature/the universe/the planet/etc.?",
        "Are we all connected in some way or another, and is this connection means anything to us?",
        "Can we ever be sure what other people are thinking or feeling?",
        "Where does morality come from?",
        "Are people inherently good or evil? Why?",
        "Do people really have free will (the ability to choose exactly what they want)? Or are we all just acting out roles given to us by nature and nurture (our environment)?",
        "Why can’t a person be in two places at the same time?",
        "Why is it called common sense if it’s so rare?",
        "If a person owns a piece of land do they own it all the way down to the core of the earth?",
        "Are there really such things as accidents? Is there any such thing as a coincidence?",
        "If people evolved from apes, why are there still apes?",
        "Being a grown-up isn’t half as fun as growing up, would you agree with this statement?",
        "Do you sometimes sing or hum to yourself when alone, if so who is listening then?",
        "Is ignorance really bliss?",
        "Is it possible for a man to be pregnant with other species?”",
        "What came first, the chicken or the egg?",
        "If you’re born in Germany, raised in the U.S., and vacation in Mexico, where are you from?”",
        "What would happen if Pinocchio said ‘My nose will grow now’?”",
        "Why do we teach kids that violence is not the answer and then have them read about wars in school that solved America’s problems?”",
        "If all of the nations in the world are in debt, where did all of the money go?”",
        "If electricity comes from electrons, does morality comes from morons?",
        "If money is the root of all evil, why do they still ask in church?",
        "How to die without knowing that we are dead?",
        "If it’s true that we are here to help others, then what exactly are the others here for?",
        "If you hire a guy to kill you, will it be ruled out as suicide or murder?",
        "If man evolved from monkeys and apes, why do we still have monkeys and apes?",
        "If the moon has earthquakes, what do they call moonwalks?",
        "If there aren’t aliens then who are the audience?",
        "If you get scared half to death, then half to death means you have a quarter a life left?",
        "Who is the most intelligent person in the world that no one ever knows?",
        "How big is the world’s smallest philosophical thought?",
        "What’s the question with no answer called?",
        "Why life is so short yet too long to wait for death?",
        "If there is only bliss in life, do we die in the pursuit of suffering?",
        "Why doesn’t Earth fall down on Mars?",
        "If everything is connected why do we lose ourselves in love?",
        "Does knowledge make a man feel dumb?",
        "Who is the dumbest philosopher of all time?",
        "Why do people tell you when they are speechless?",
        "Is it illegal to kill an ant?",
        "How can you determine the gender of babies who are born with no private parts?",
        "Why do we think that accidents never happen to us?",
        "When you have a stomach ache, is the pain in your abdomen or in your brain?",
        "Can we really know what it feels like to be an ant?",
        "Are we thinking or feeling?",
        "Did we die already?",
        "How to prove that we are alive?",
        "If we are humans, why aren’t we behaving like humans?",
        "Where is everybody?",
        "Do animals dream?",
        "What is the animal’s biggest fantasy?",
        "Do animals have free will?",
        "Should we believe anything just because others do? Why or why not?",
        "Why do so many people believe in religion even though nothing good happens?",
        "Should we trust our senses?",
        "Can we be certain of anything?",
        "Is it wrong to tell a lie?",
        "What is the difference between right and wrong?",
        "Do we have souls?",
        "What is the nature of reality?",
        "Why do people cheat and steal?",
        "Is it possible to know the truth?",
        "Can science explain everything in our universe? (Or is there something else?)",
        "What is the difference between our mind, body, and soul?",
        "What if there are more than three dimensions?",
        "Does time have a beginning and an end?",
        "If time doesn’t have an end, does that mean our lives are already over?",
        "What is the nature of the universe?",
        "What would be the most philosophical piece of advice you could give a newborn infant?",
        "If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone and why haven’t you told them yet?",
        "Why do we think we don’t know everything when nobody knows everything?",
        "Is it better to stay with someone who treats you badly or be alone?",
        "If you could choose to never get sick, would you?",
        "What is your definition of success? Does money make you happy?",
        "Do you believe good things happen only to good people?",
        "Do you believe in miracles and magic?",
        "What if you could only see the world through your phone screen? Would it still be the same world?",
        "What would you do, if you have the chance to live forever?",
        "Before we were born what were we?",
        "What happens if we live forever?",
        "Is it truly possible to see the clear perspective of others?",
        "How to feel exactly how others feel?",
        "How to know exactly what others think about us?",
        "What if wake up tomorrow without one of our senses?",
        "What would it feel like, if a man were a woman?",
        "Is there anything to use besides our senses?",
        "What is the purpose behind whatever we think, feel and act?",
        "What is sixth sense?",
        "Why everything in life seems so certain yet unknown at the same time?",
        "What is the whole point?",
        "What if you are wasting your time by thinking?",
        "How do we know when we are free?",
        "Are we slaves to anything or anyone?",
        "What is the philosophy of life?",
        "Is life a coincidence?",
        "If you could design your life, how would you do it?",
        "Is there a plan for life?",
        "How do we embrace life’s absurdity?",
        "Why life is so uncertain?",
        "How to live a simple life in today’s society?",
        "Is living life well all about finding balance?",
        "Why do you want to be successful and improve your life?",
        "What does it mean to live life to the fullest?",
        "When will the regular world come back to live a real life?",
        "Is this life just a massive holographic game?",
        "Why am I conscious?",
        "If I am conscious why am I so ignorant?",
        "What is consciousness?",
        "What is beyond our consciousness?",
        "Are consciousness and intelligence have to do something with god?",
        "How to focus on your consciousness during your life?",
        "When should we trust others above our own consciousness?",
        "Is there any reality beyond consciousness?",
        "Am I becoming conscious without my involvement?",
        "If ignorance is bliss, what consciousness’s purpose is?",
        "What is the truth?",
        "Is an absolute truth possible?",
        "Are there truths and what is the ultimate truth?",
        "Is there any objective truth or is truth merely relative to our subconscious bias?",
        "What is the harsh truth you would hide from everyone?",
        "How to know if someone is telling the truth?",
        "How much of truth is really true?",
        "Why did no one ever discover the ultimate truth?",
        "What if the truth and lies are not correct?",
        "Are we misleading ourselves from the greatest truth?",
        "What if the truth of life is death?",
        "Do religions other than our own have something to teach us?",
        "Are there any purposes for holding beliefs?",
        "Is there any nature that our senses cannot detect?",
        "Is happiness a state of mind, a consequence, or an end?",
        "Why should we choose to live life?",
        "Is the present moment all that we have?",
        "Why do you want to feel good all the time?",
        "What is enlightenment?",
        "What is being?",
        "What is meant by a spiritual being and philosophical being?",
        "How can you describe the concept of modes of existence?",
        "Is there any place for use of old technology and old science in modern today? ",
        "Is technology going to be the reason for the apocalypse?",
        "What is the first technological device in ancient times?",
        "Is ancient technology more advanced than modern technology?",
        "Is technology being discovered or invented?",
        "If technological scientists invent flying cars, will all other transportation vanish?",
        "Why no one is taking serious about artificial intelligence?",
        "Does the modern invention of smartphones cripple the human brain?",
        "Where does the philosophy of spirituality and philosophy of science and technology intersect?",
        "What is good and evil in an intellectual sense?",
        "Why do we feel good when we experience beauty?",
        "What does it mean to have a good character?",
        "How important it is to have good friends?",
        "How do we figure out, what is most important to us and for the good cause of the world?",
        "Do we mostly regret the things we did or the things we wished we did?",
        "Do people get closed-minded as they age?",
        "Is our worldview mostly based on our emotions?",
        "Is tribalism influences our own society?",
        "Is boredom necessarily bad?",
        "Who am I?",
        "What does it mean to be conscious?",
        "Are people inherently selfish?",
        "Do we have authentic selves?",
        "Is there just oneself or there are multiple selves within one person?",
        "Why do we feel lonely?",
        "Why do some people prefer to live alone?",
        "How do we create a personal philosophy?",
        "Is there any way to prove anyone else is conscious?",
        "Is our physical health tied up with our emotional health and vice versa?",
        "How important is it to reflect on our lives?",
        "When do we stop thinking other than after death?",
        "What is nothingness?",
        "Are we all just living in a loop?",
        "Why are we altruistic to one another?",
        "How can we fully enjoy nature?",
        "How can we reduce our egos?",
        "Where does emotional suffering come from?",
        "Are we on the path to destruction and ending our own civilization?",
        "Is faith truly a leap?",
        "Why is the sense of home so important to us?",
        "What makes humans distinct in the human kingdom?",
        "Do the cosmos have an end?",
        "Is the cosmos inherently chaotic or ordered, is there even a difference?",
        "Is there a reality beyond space and time?",
        "Are we the first civilization in the galaxy?",
        "Are humans significant relative to the entire cosmos?",
        "How vast our cosmos is?",
        "How many universes are there?",
        "Is the multiverse exists?",
        "How long does space-time continue?",
        "Is our own universe an illusion?",
        "Do we exist as a better version of ourselves in a parallel universe or worse?",
        "How to end our pain and suffering?",
        "Is chaos just?",
        "Why are we fearful of things?",
        "Why do we worry about the things that we cannot control?",
        "How can we reduce our appetites?",
        "Why do we ignore the things that are in our control yet choose to suffer?",
        "Why do we fulfill our own lots before others’ needs?",
        "Are values more important than being right?",
        "Why are we so cautious of others?",
        "Should we live out our emotions completely or reduce them?",
        "Does mathematics exist beyond human convention?",
        "What is the difference between science and philosophy?",
        "Was the big bang just an accident?",
        "Will robots become conscious one day?",
        "Why can’t we see evidence of alien life?",
        "If aliens exist, What if they’re somewhere wondering “if aliens exist”?",
        "Where is everybody?",
        "Are we programmed to live this life?",
        "Is the perfect answer to every question between zero and infinity? ",
        "What if the ideas in our heads itself aliens?",
        "Is the present-day human individual a special part of nature?",
        "What should values only base on human convention?",
        "How do we make decisions and form beliefs about issues that are inherently irrational?",
        "Is there a struggle for equilibrium in nature?",
        "What are the risks and benefits of being spontaneous?",
        "How can we find our inner child?",
        "Should we allow the environment to dictate our moods?",
        "Do we have a moral obligation to intervene in other people’s businesses?",
        "How important is it to think for ourselves?",
        "Should we consider our lives simply as future memories?",
        "When does society realize its foolishness?",
        "Why do people harm each other?",
        "What is the ultimate motive of society?",
        "Why does negativity spread more rapidly than the good in society?",
        "Who is society?",
        "What role an individual plays in society?",
        "Why society is evil for good people?",
        "Why only 1% of the population is rich and the rest is doomed to poverty?",
        "How to bring everyone into unity?",
        "Does the civilization become free without being ruled by any government or kings or higher officials?",
        "Why do people need to be controlled by others If everyone is a human?",
        "Why are you ‘you’ and furthermore what are you?",
        "How to listen to every thought we think?",
        "Is the mind the same as the brain, or do we have souls?",
        "Can computers think, or fall in love?",
        "Can computers be creative?",
        "Can robots fall in love?",
        "If tomorrow is the end of humanity, and today you got superpowers with only one chance to use them what would you do?",
        "What if every human becomes a deep philosopher?",
        "Can Insanity is the real force behind crazy innovations?",
        "How honest should we be to the children about real life?",
        "Is anyone really here, if so how do we really know?",
        "Is reality a dream?",
        "What does a dream feel like in real?",
        "Is everything real or an illusion?",
        "Can we really predict the future?",
        "How to create one’s reality?",
        "If everything feels real, why doesn’t it exist? ",
        "What makes reality different from illusion?",
        "What if, in reality, we are not humans, but toys being played with by some extraterrestrial bodies?",
        "What and who a man is?",
        "Are we really here?",
        "What does it mean to forgive truly somebody?",
        "Why do we think that we control our future?",
        "Shall we protect those who cannot speak for themselves?",
        "What does it mean to be a citizen of the world?",
        "What pursuits inspire a man to create his future?",
        "Where do thoughts come from?",
        "What is the core idea of life?",
        "Can we become ignorant once if we expanded our consciousness?",
        "Why there is always a conflict between religion and science?",
        "What is the philosophy of religion other than the concept of god?",
        "If God doesn’t exist, do all the religious people get heartache?",
        "If religion and spirituality are not the same, why god is their connection?",
        "What happens to religions, spirituality, science, and philosophy if the existence of god gets proved wrong?",
        "What is religion according to scientists and philosophers?",
        "What if people are just wasting their time by believing in religion?",
        "If the concept of religion is wrong, does the existence of all the religious people meaningless? ",
        "Why do people follow religions?",
        "What every religion is trying to preach to humanity?",
        "Does every religion one?",
        "Why do we decide what we decide? ",
        "How do we make our life choices?",
        "Are we progressing or trying to ourselves?",
        "Are there universal moral beliefs across all cultures?",
        "When do we discover inner peace?",
        "When to choose peace and suffering?",
        "Why it is so difficult not to worry about ourselves and others?",
        "Do we owe back anything to the society we grew back in?",
        "What is the purpose of having hope for the future?",
        "What is to be a human?",
        "Is there anything more important than our history for humans?",
        "Are people stories, memories, and nothing else?",
        "Do humans inherently destroy themselves?",
        "Should our society have complete freedom of speech without any restriction?",
        "Why do people desire power and wealth?",
        "Is having power corrupt souls?",
        "What does it mean to be a healthy person?",
        "Do other people corrupt our souls or do we corrupt our own?",
        "What is the purpose of humanity in this cosmos?",
        "Why do we always think of something?",
        "What does being dead feel like?",
        "How many particles are in a fist of sand?",
        "How many sand particles are there in the universe?",
        "Debatable philosophical Questions",
        "Do Insects feel pain?",
        "Why do so many people and animals suffer terrible things?",
        "Is the future yet to be written?",
        "Is everything predestined by God?",
        "Do we own anything for real?",
        "Is happiness the most important goal in life?",
        "Is happiness about fulfillment in life?",
        "What makes a human happy forever?",
        "Is happiness a choice? ",
        "What is the happiest moment in the history of the cosmos?",
        "Why do wise men never talk about happiness?",
        "What kind of life brings happiness into one’s life?",
        "Does happiness be the ultimate pursuit of one’s life?",
        "Why do some people are happier than others?",
        "Do we need to seek happiness or simply live?",
        "Are we discovering everything or creating everything?",
        "Why are we here?",
        "Do we have immaterial minds or physical brains?",
        "Where do our thoughts go when we forget things?",
        "Is there such thing as philosophical health or well-being?",
        "Will science and philosophy allow us to overcome our mind’s limitations?",
        "What is the goal of animals?",
        "Why do we forget our dreams?",
        "How to be reborn after death?",
        "How many possible answers to a question and which one among them is the ultimate?",
        "Is there a god?",
        "What if we are outliving the god?",
        "Do god and man are the same?",
        "What is the philosophy of god?",
        "Was god a mathematician?",
        "If there is a god, how are we so sure that it’s a he but not she?",
        "Why are some people feel happy that they do not believe God exists?",
        "What is more important between god and our belief and god?",
        "What is the relationship between God and our consciousness?",
        "Are the cosmos itself god?",
        "What happens if the obligations conflict with morality?",
        "Is there such a thing as moral instinct?",
        "Do people possess a moral compass?",
        "Are our moral values derived from our aesthetic values?",
        "Is it necessary to be occupied with morals in order to live a peaceful life?",
        "How to make morality, a part of human nature?",
        "How essential it is to be moral in a world full of dishonesty?",
        "Can we teach morals to people and how to improve morality in our own life?",
        "Does the concept of morality depend on reason?",
        "What is the psychology of moral principles in the philosophy of life?",
        "What is the moral responsibility of a human in the nature he lives in?",
        "How effective a person’s life can be if he is full of morals rather than truth?",
        "Why do we need family when alone bringing peace?",
        "Is it better to adopt kids to avoid overpopulation?",
        "What moral lessons would you teach your kids as a father or mother?",
        "Why it is important to start a family?",
        "When is the right age to marry and lead a family?",
        "Do you think your parents were good parents?",
        "Where does the tree of your ancestors’ family begin?",
        "What makes your family different from others in your society?",
        "What kind of father or mother ought you to become?",
        "How do you raise your kids if they are opposite gender to one?",
        "What is the importance of political norms in the age of modern philosophy?",
        "What values lead a person to the current political beliefs?",
        "Can we separate political issues from the people who hold them?",
        "What forms of political arguments bring society into its harmonious state?",
        "What do you learn from politics?",
        "Is the world doomed to be ruled by corrupt politicians?",
        "What are your views on the political issues, and what change do you desire from the current system?",
        "What could be done to improve each other’s lives without politics?",
        "How to unite every nation and creed with a simple act of kindness rather than political agendas?",
        "What is the heart of the nation’s issues, for you as an individual?",
        "What makes philosophers fearful?",
        "Why do we fear for the things that don’t exist?",
        "What is the source of fear?",
        "Is fear drives a man to discover his inner potential?",
        "If fear doesn’t exist, do humans lose their morals?",
        "When do we overcome our fear of uncertainty?",
        "How can a person be fearful if he doesn’t even know what it is?",
        "If we are completely ignorant, do we ignore our fears too?",
        "What is the difference between fear and phobia?",
        "What are the man’s biggest fears?",
        "What happens if we are at our extreme levels of fear?",
        "Is death painful?",
        "Is there an afterlife?",
        "What is the best way to die?",
        "Are we all just getting ready to die?",
        "Can we decide when to die?",
        "Is it logical to fear the death of our loved ones?",
        "Should we mourn or celebrate the death?",
        "What if the death is not a death at all?",
        "How should we think about our inevitable death?",
        "Do we need to be fearful of death?",
        "Why do some people die suddenly without any reason?",
        "Are we being tormented or live happily after death?",
        "What is your perspective on death?",
        "Do philosophers afraid of death?",
        "Is death a dreamless sleep or a path to an afterlife?",
        "Do we have bodies or disembodied minds after death?",
        "Do we call ourselves humans after death?",
        "Do just our bodies die or our souls too?",
        "Would you kill yourself to save another life?",
        "Can we understand good without evil?",
        "Is there a purpose for our life?",
        "What would you choose between “yes or no” without a question?",
        "Is there such thing as destiny?",
        "Do we really need love to survive?",
        "Is it always good to be happy?",
        "Do you think philosophy and science are the same?",
        "Do a man and a woman make a good life out of misery?",
        "Is it ok to be nothing rather than everything in a life of uncertainty?",
        "Philosophical questions about free will",
        "Are freedom and death the same?",
        "How much freedom should people have?",
        "What does it mean to be free?",
        "Is everyone in the universe equally free?",
        "Where do you receive your eternal freedom?",
        "Can freedom become a man’s prison once he achieves it?",
        "What happens if everyone gets their entire freedom?",
        "How much freedom is sufficient for humans to be happy and fulfilled?",
        "What comes to your mind when you think about freedom?",
        "What if all the people in the world have empathy and do not hurt each other?",
        "Why some people are more honest than others?",
        "Should thieves be punished if they are poor for stealing from someone?",
        "What makes humans act ethically and morally?",
        "Is it ok to lie when lying is the choice? And when should people lie?",
        "When should an ethical person stay away from a toxic society?",
        "Do everyone in the world has ethical values, if not how important it is to possess them?",
        "Do ethical values are inherently acquired or do we need to develop as we age?",
        "Why we should cultivate ethics when everyone has their own philosophy of life?",
        "Do you consider yourself an ethical person?",
        "What is the point of education if an educated person makes himself fool in front of an illiterate?",
        "What makes an educated person different from an illiterate when common sense is the key?",
        "Why do people need education?",
        "What kind of education is the best food for the soul?",
        "Why do most educated people in the world begin to realize that the education system is completely worthless?",
        "When does education serve its philosophy for the common good of society without the involvement of money or business?",
        "What is the role of a teacher in education if he is also ignorant of this cosmic universe?",
        "Which is better self-education or traditional education?",
        "What does a teacher think of his student if he outreaches his master in all areas of life?",
        "Does education bring suffering a meaning?",
        "Who do we call friends?",
        "How to know the true motive of a friend when he or she constantly flatters you?",
        "Do we need friendship for the love of others or for ourselves?",
        "Is a life with friends drive a better meaning in ourselves?",
        "How to tell a person if he or she is a good friend?",
        "Do ancient philosophers believe in the concept of true friendship?",
        "How long does an average friendship stay?",
        "What is the biggest philosophical concern about friendship?",
        "Do intellectual friends discuss philosophical questions during their fun time?",
        "Is friendship a genetic leftover?",
        "What is the ethical significance behind friendship?",
        "What is justice as per ancient and modern philosophy?",
        "How do we arrive at the matter of justice?",
        "What is justice philosophically?",
        "What kind of right is justice?",
        "Is justice a human need?",
        "Why is justice so difficult when everyone is after right and wrong?",
        "What makes a good judge in this corrupted society?",
        "Is justice objective or personal?",
        "What is the role of justice in the philosophy of righteousness?",
        "How can one promote justice in society?",
        "If the artwork is a judge, how would it critique itself?",
        "Does every art represent a significant meaning in life?",
        "Why there is a deep relationship between art and philosophy?",
        "What makes art different from philosophy?",
        "What is the most spectacular art theft in the world?",
        "What would life be without art?",
        "Why art is completely mysterious and strange in so many ways?",
        "Why Mona Lisa art is so famous?",
        "Can a good fake be art too?",
        "Is graffiti art?",
        "Can anybody be an artist?",
        "Why are the most famous artists male?",
        "Is time an objective phenomenon?",
        "Does time really exists or is it just something we sense?",
        "Is time finite or infinite?",
        "Do you think that time is the greatest philosophical mystery ever encountered by mankind?",
        "Is it possible to measure time?",
        "Does time have a definite form?",
        "How to find the origin of time?",
        "Are the concepts of past, present, and future real?",
        "Does time flow?",
        "Is time travel possible?",
        "Does time exist after all?",
        "What does money mean to you?",
        "Why money is ruling the world instead of morals?",
        "Are you open to receiving money?",
        "How much money do you want to earn by the end of your 50s?",
        "How much money is too much?",
        "What do you believe about rich people and poor people?",
        "Why rich is rich and the poor ‘poor’?",
        "If there is no concept of money, what would people do?",
        "Does earning money bring happiness?",
        "Why are all the successful rich people do not satisfy with money?",
        "Is nature good and beautiful only when it is beneficial to humans?",
        "How do we see beauty in all things?",
        "Why you should be gentle with people?",
        "Why is beauty associated with morality?",
        "If there is no beauty in one’s soul, does a person unworthy to live?",
        "Why a person with beauty is so simple and elite in his presence?",
        "Why do people think beautiful people have moral upright?",
        "How do we differentiate a soul with beauty and evil tantrums?",
        "Do beautiful people always stand alone and wonder about beauty?",
        "Do you consider yourself beautiful?",
        "Do people really need other people in their lives?",
        "Is there anything more important than our relationships with each other?",
        "Do we ever have the right to say to someone else what he or she should do?",
        "Should we respect the opinions of others in we find wrong?",
        "Why do we judge ourselves and others?",
        "How do we move forward when we lost someone special?",
        "Why would we worry about what others think about us?",
        "How do we become more sympathetic towards others?",
        "What philosophical approach is best suited for a lifelong relationship?",
        "Why do people mourn and grieve when their loved ones die?",
        "What is existence, and why did it occur?",
        "What is the meaning of our existence?",
        "Is existence weird?",
        "Why do we have existential crisis?",
        "Do ideas are the only things that exists?",
        "How can we truly change the perspectives on our lives?",
        "How should we prepare for our inevitable death?",
        "Is adversity truly the worse thing in our lives?",
        "Why do we enjoy a comfortable life and is it actually that great?",
        "Who decides what we should or shouldn’t do in our daily lives?",
        "What is meaning?",
        "What is essence?",
        "Are we free?",
        "Do we have a soul?",
        "Is there an afterlife?",
        "Are there objective truths about the world?",
        "Is our reality real or a simulation?",
        "What is consciousness?",
        "Can we trust our senses to give us the truth?",
        "Is there free will or do our actions already been determined?",
        "Is there a God, or some sort of higher being that created the universe? If so, what does it look like and what does it want from us?",
        "What happens when we die?",
        "How did everything get started and who or what set it in motion?",
    ]
}; 